### ISSUE TITLE
Add option to refresh directory tree

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/vscode-ev3dev-browser#35]
Currently, when I create a file outside of VSCode (e.g., `wget` or `curl` a setup script) I must disconnect and reconnect to force the tree to refresh. It would be helpful if I could instead click a "refresh" button to do so on-the-fly.

**Comment by dlech** [comment]
You can actually currently do this by collapsing and expanding directories. But having a refresh icon would be a bit more obvious.

And, if you go back to the [beginning of time](https://github.com/ev3dev/vscode-ev3dev-browser/commit/fd9c59fa57788dab8344ac6f6d1688056948338a) there was actually a refresh command, but I removed it somewhere along the way because it was broken.

**Comment by WasabiFan** [comment]
> You can actually currently do this by collapsing and expanding directories. But having a refresh icon would be a bit more obvious.

Oh, that makes a lot more sense... I was trying that to no avail but was actually expanding the device node instead of the file node. That's certainly a good workaround.

**Comment by dlech** [comment]
It should work with individual directories as well. At least it used to...

**Comment by WasabiFan** [comment]
I think you're right... I was just working with a root-level file, so the `home` directory was the only one which had relevant children, and I clicked the wrong node.
