### ISSUE TITLE
Can't get screenshot from device right menu

### ISSUE THREAD

**Issue by RustomMurad** [ev3dev/vscode-ev3dev-browser#88]
**Describe the bug**
When I tried to take screenshot from ev3dev right-click menu, I got every time following error message:
Unable to open 'ev3dev-2019-xx.png': Cannot read property 'overwrite' of null.

**To Reproduce**
1. Start/boot ev3 smart brick with ev3dev-stretch-ev3-generic-2019-03-03.img
1. Open VS Code project
2. Establish WiFi connection with ev3 smart brick
2. Right click on device - ev3dev
3. Click on Take screenshot
4. See error:Unable to open 'ev3dev-2019-xx.png': Cannot read property 'overwrite' of null.

**Expected behavior**
VS Code should rise window with ev3dev-2019-xx.png image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: macOS version 10.13.6 (17G8030)
 - VS Code version 1.38.1
 - Node.js  v8.16.1 (npm v6.4.1) - lts/carbon 

**Additional context**

**Comment by dlech** [comment]
Thanks for the bug report. I am able to reproduce the problem.

I'm guessing that something changed in VS Code. The error comes from VS Code and not this extension.

https://github.com/microsoft/vscode/blob/e4a66a86981b65e86486ef433d57fef6c9d18f93/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L931

It is working again in the Insiders version, so I expect this will be fixed in the next VS Code release.

**Comment by RustomMurad** [comment]
I downgraded VSCode to 1.37.1. Got working Take screenshot device right click menu item. Thanks for your tip.

**Comment by dlech** [comment]
New releases are working, so closing.
